### ISSUE TITLE
the main is not fully uploaded

### ISSUE THREAD

**Issue by walid0912** [lotfiferaga/Mobile_Phone_Gen#3]
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
// ON DEFINIT LE TYPE BOOLEAN "VRAI" et "FAUX"
#define SEEK_SET 0
#define SEEK_CUR 1
#define SEEK_END 2
typedef struct _iobuf FILE;
enum boolean {true,false};
typedef enum boolean boolean;

int main()
{

    int choix=0;
    do
    {
        srand(time(NULL));
         menu(choix);
    }
    while(choix!=9);

}

**Comment by lotfiferaga** [comment]
working on it

**Comment by walid0912** [comment]
done
